### ISSUE TITLE
Only one track from each album is moved.

### ISSUE THREAD

**Issue by ghost** [SuperToma/takeout-google-play-music-classify#1]
Followed the install and usage instructions exactly using both python2 and python3.

When running the script the following error is thrown:

`Traceback (most recent call last):
  File "classify_mp3.py", line 75, in <module>
    album = (f"({year}) " if year is not None else "") + album
TypeError: can only concatenate str (not "NoneType") to str`

The script creates a folder for each album, and seems to move one track for each album into the right folder (I say 'seems to' as I haven't checked every folder yet).

Environment:
Ubuntu Budgie
Linux 5.4.0-65-generic #73-Ubuntu 
Python 2.7.18
Python 3.8.5
pip 20.3.4 (pip2)
pip 20.0.2 (pip3)

Please let me know if I'm missing anything and thanks for writing this.

**Comment by anthx** [comment]
I suspect some of your tracks don't have album in the ID3 tag or in the format that it can guess based on the filename. 

My version should fix that: https://github.com/anthx/takeout-google-play-music-classify or wait for @SuperToma to merge my PR. 

The reason only 1 track was moved is that the script stops if it encounters some error in saving or runtime errors.

**Comment by ghost** [comment]
> I suspect some of your tracks don't have album in the ID3 tag or in the format that it can guess based on the filename.

Cheers for the reply and advice.

I used your fork and it does move all the tracks quite well and as expected. 

Thanks again.
